CREATE USER 'mac'@'localhost' IDENTIFIED BY 'mac';
GRANT ALL PRIVILEGES ON *.* TO 'mac'@'localhost' WITH GRANT OPTION;
CREATE USER 'mac'@'%' IDENTIFIED BY 'mac';
GRANT ALL PRIVILEGES ON *.* TO 'mac'@'%' WITH GRANT OPTION;